apiVersion: v1
kind: Service
metadata:
  name: {{ include "ejemplo.fullname" . }}
  labels:
    {{- include "ejemplo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - nodePort: {{ .Values.service.exposePort }}
      port: {{ .Values.service.internalPort }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "ejemplo.selectorLabels" . | nindent 4 }}
